import ProjectInfo from '@/types/project_types';

export default [
  new ProjectInfo('webgpu_ocean',
                  () => import('@/content/projects/webgpu_ocean/article.vue'),
                  'WebGPU Ocean Scene',
                  '/images/projects/webgpu_ocean/icon.png',
                  new Date('2026/09/03'),
                  new Date('2026/09/03')),
  new ProjectInfo('heart_sdf',
                  () => import('@/content/projects/heart_sdf/article.vue'),
                  'Anatomy of a Heart (SDF)',
                  '/images/projects/sdf/icon.png',
                  new Date('2026/01/29'),
                  new Date('2026/01/31')),
  new ProjectInfo('match_three',
                  () => import('@/content/projects/match_three/article.vue'),
                  'Match-3 Game',
                  '/images/projects/match_three/icon.png',
                  new Date('2025/05/27'),
                  new Date('2026/03/16')),
  new ProjectInfo('renu',
                  () => import('@/content/projects/renu/article.vue'),
                  'RENU - Imagine Cup 2013 @ RIT',
                  '/images/projects/renu/icon.png',
                  new Date('2012/12/01'),
                  new Date('2012/12/01')),
  new ProjectInfo('metaballs',
                  () => import('@/content/projects/metaballs/article.vue'),
                  'WebGL Metaballs',
                  '/images/projects/metaballs/icon.png',
                  new Date('2012/10/08'),
                  new Date('2025/06/18')),
  new ProjectInfo('flocking',
                  () => import('@/content/projects/flocking/article.vue'),
                  'WebGL Flocking',
                  '/images/projects/flocking/icon.png',
                  new Date('2012/10/05'),
                  new Date('2025/07/07')),
  new ProjectInfo('proto_engine',
                  () => import('@/content/projects/proto_engine/article.vue'),
                  'WebGL Proto-Engine',
                  '/images/projects/proto_engine/icon.png',
                  new Date('2012/09/01'),
                  new Date('2025/06/25')),
];
